FROM nginx:alpine

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

# Exposes port 443
EXPOSE 443

# Starts Nginx with default conf and keeps it running
ENTRYPOINT [ "nginx", "-c", "/etc/nginx/nginx.conf" ]
CMD ["-g", "daemon off;"]