"""Initial migration

Revision ID: 41ed5f89403d
Revises: 
Create Date: 2026-03-29 07:02:50.381948

"""
from typing import Sequence, Union
from uuid import uuid4

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = '41ed5f89403d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dining_halls',
    sa.Column('id', sa.UUID(), nullable=False, server_default=text("gen_random_uuid()")),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('food',
    sa.Column('dining_hall_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('nutrition_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('elo_rating', sa.Float(), nullable=False, server_default=sa.text('1000.0')),
    sa.ForeignKeyConstraint(['dining_hall_id'], ['dining_halls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dining_hall_id', 'name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food')
    op.drop_table('dining_halls')
    # ### end Alembic commands ###
