"""Initial migration

Revision ID: 5be13a1a5f89
Revises: 
Create Date: 2026-04-11 00:40:52.771312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5be13a1a5f89'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dining_halls',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('req_id', sa.TEXT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('req_id')
    )
    op.create_index(op.f('ix_dining_halls_name'), 'dining_halls', ['name'], unique=True)
    op.create_table('dishes',
    sa.Column('dining_hall_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('nutrition_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('elo_rating', sa.Float(), server_default=sa.text('1000.0'), nullable=False),
    sa.Column('matches', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['dining_hall_id'], ['dining_halls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dining_hall_id', 'name')
    )
    op.create_index('ix_dishes_dining_hall_id_elo_rating', 'dishes', ['dining_hall_id', 'elo_rating'], unique=False)
    op.create_index('ix_dishes_elo_rating', 'dishes', ['elo_rating'], unique=False)
    op.create_index('ix_dishes_matches', 'dishes', ['matches'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dishes_elo_rating', table_name='dishes')
    op.drop_index('ix_dishes_dining_hall_id_elo_rating', table_name='dishes')
    op.drop_index('ix_dishes_matches', table_name='dishes')
    op.drop_table('dishes')
    op.drop_index(op.f('ix_dining_halls_name'), table_name='dining_halls')
    op.drop_table('dining_halls')
    # ### end Alembic commands ###
